# Generated by Django 5.0.14 on 2026-02-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_notebook_conversation_notebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='notebook',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
