# Generated by Django 5.2.10 on 2026-02-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(blank=True, choices=[('pdf', 'PDF Document'), ('docx', 'Word Document'), ('txt', 'Text File'), ('md', 'Markdown File'), ('audio', 'Audio File'), ('video', 'Video File'), ('url', 'Web URL')], default='txt', max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, default='Untitled', max_length=255),
        ),
    ]
