# Generated by Django 5.0.14 on 2026-02-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_file_type_alter_document_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(blank=True, choices=[('pdf', 'PDF Document'), ('docx', 'Word Document'), ('pptx', 'PowerPoint'), ('txt', 'Text File'), ('md', 'Markdown File'), ('image', 'Image'), ('audio', 'Audio File'), ('video', 'Video File'), ('url', 'Web URL')], default='txt', max_length=10),
        ),
    ]
