# Generated by Django 5.2.10 on 2026-02-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebookguide',
            name='guide_type',
            field=models.CharField(choices=[('faq', 'Frequently Asked Questions'), ('study', 'Study Guide'), ('summary', 'Briefing Document'), ('toc', 'Table of Contents'), ('audio', 'Audio Overview')], max_length=20),
        ),
    ]
