# Generated by Django 5.2.10 on 2026-02-08 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_notebook_description_notebook_is_public'),
        ('documents', '0004_alter_notebookguide_guide_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebookguide',
            name='notebook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='chat.notebook'),
        ),
    ]
